//
// Created by alexoxorn on 5/14/24.
//

#ifndef CHAOTIC_CORE_EFFECT_CONSTANTS_H
#define CHAOTIC_CORE_EFFECT_CONSTANTS_H

#include "common.h"

enum class EVENT {
    STARTUP = 1000,
    LEAVE_FIELD_P,
    LEAVE_FIELD,
    LEAVE_GRAVE,
    TO_HAND,
    TO_DECK,
    TO_GRAVE,
    REMOVE,
    DISCARD,
    SACRIFICE,
    DESTROYED,
    MOVE,
    DRAW,
    PRE_LOCATION_REVEAL,
    ACTIVATED_LOCATION,
    ADJUST,
    CREATURE_MOVE,
    DAMAGE_DEALT,
    DAMAGE_RECEIVED,
    HEALED,
    DESTROY,

    PHASE = BIT(13),
    PHASE_LOCATION = PHASE | +PHASE::LOCATION_STEP,
    PHASE_ACTION = PHASE | +PHASE::ACTION_STEP,
    PHASE_RECOVERY = PHASE | +PHASE::RECOVERY_STEP,
    PHASE_START = BIT(14),
    PHASE_START_LOCATION = PHASE_START | +PHASE::LOCATION_STEP,
    PHASE_START_ACTION = PHASE_START | +PHASE::ACTION_STEP,
    PHASE_START_RECOVERY = PHASE_START | +PHASE::RECOVERY_STEP,

    PHASE_START_ENGAGEMENT = PHASE_START | +PHASE::ENGAGEMENT,
    PHASE_START_BATTLEGEAR = PHASE_START | +PHASE::REVEAL_BATTLE,
    PHASE_START_BEGINNING_COMBAT = PHASE_START | +PHASE::BEGINNING_OF_COMBAT,
    PHASE_START_INITIATIVE = PHASE_START | +PHASE::INITIATIVE,
    PHASE_START_STRIKE = PHASE_START | +PHASE::STRIKE_PHASE,
};

enum class REASON {
    NONE = 0,
    DESTROY = BIT(1),
    REMOVED = BIT(2),
    EFFECT = BIT(3),
    COST = BIT(4),
    ADJUST = BIT(5),
    LOST_TARGET = BIT(6),
    RULE = BIT(7),
    BATTLE_GEAR_FLIP = BIT(8),
    DISCARD = BIT(9),
    DAMAGE = BIT(10),
    RETURN = BIT(11),
    REDIRECT = BIT(12),
    SACRIFICE = BIT(13),
    DRAW = BIT(13),
    PLAYER_ACTION = BIT(14),
    FIRE = BIT(15),
    AIR = BIT(16),
    EARTH = BIT(17),
    WATER = BIT(18),
    WISDOM = BIT(19),
    COURAGE = BIT(20),
    STRENGTH = BIT(21),
    SPEED = BIT(22),
    MUGIC = BIT(23),
    ATTACK = BIT(25),
};

enum class EFFECT {
    PUBLIC,
    START_GAME_FACEUP,
    MUST_MOVE_INTO,
    MUST_ATTACK,
    CANNOT_MOVE,
    CAN_MOVE_ANY_UNOCCUPIED,
    SWIFT,
    RANGE,
    SURPRISE,
    LOST_INITIATIVE,
    RANDOM_ATTACK,
    INDESTRUCTIBLE,
};

#endif // CHAOTIC_CORE_EFFECT_CONSTANTS_H
