from enum import IntEnum, IntFlag, auto


def BIT(x):
    return 1 << (x - 1)


class LOCATION(IntFlag):
    NONE = 0
    ATTACK_DECK = BIT(1)
    ATTACK_DISCARD = BIT(2)
    FIELD = BIT(3)
    MUGIC_HAND = BIT(4)
    ATTACK_HAND = BIT(5)
    GENERAL_DISCARD = BIT(6)
    REMOVED = BIT(7)
    BURST = BIT(8)
    ACTIVE_LOCATION = BIT(9)
    LOCATION_DECK = BIT(10)

    GLOBAL = FIELD | GENERAL_DISCARD | LOCATION_DECK
    HAND = ATTACK_HAND | MUGIC_HAND
    DECK = ATTACK_DECK | LOCATION_DECK
    GRAVE = ATTACK_DISCARD | GENERAL_DISCARD
    VECTOR_AREA = DECK | GRAVE | HAND | REMOVED
    BOTTOM_ATTACK_DECK = ATTACK_DECK | BIT(17)
    SHUFFLE_ATTACK_DECK = ATTACK_DECK | BIT(18)
    BOTTOM_LOCATION_DECK = LOCATION_DECK | BIT(17)
    SHUFFLE_LOCATION_DECK = LOCATION_DECK | BIT(18)


class POSITION(IntFlag):
    NONE = 0
    FACE_UP = BIT(1)
    FACE_DOWN = BIT(2)


class SUPERTYPE(IntEnum):
    CREATURE = 0
    BATTLE_GEAR = 1
    MUGIC = 2
    LOCATION = 3
    ATTACK = 4


class SUBTYPE(IntFlag):
    WARRIOR = BIT(1)
    ROYAL = BIT(2)
    GUARDIAN = BIT(3)
    ETHEREAL = BIT(4)
    ELITE = BIT(5)
    SCOUT = BIT(6)
    ELEMENTALIST = BIT(7)
    CARETAKER = BIT(8)
    COMMANDER = BIT(9)
    CONQUEROR = BIT(10)
    TASKMASTER = BIT(11)
    NOBLE = BIT(12)
    SQUADLEADER = BIT(13)
    MANDIBLOR = BIT(14)
    MUGE = BIT(15)
    HERO = BIT(16)
    BATTLEMASTER = BIT(17)
    STRATEGIST = BIT(18)
    STALKER = BIT(19)
    CONTROLLER = BIT(20)
    AMBASSADOR = BIT(21)
    WARBEAST = BIT(22)
    CONJUROR = BIT(23)
    MINION = BIT(24)
    CHIEFTAIN = BIT(25)
    FLUIDMORPHER = BIT(26)
    KHARALL = BIT(27)
    PAST = BIT(28)
    BEAST = BIT(29)
    SHARD = BIT(30)
    MIRAGE = BIT(31)


class TRIBE(IntFlag):
    NONE = 0
    OVER_WORLD = BIT(1)
    UNDER_WORLD = BIT(2)
    MIPEDIAN = BIT(3)
    DANIAN = BIT(4)
    MARRILLIAN = BIT(5)


class PHASE(IntFlag):
    NONE = 0
    LOCATION_STEP = BIT(1)
    ACTION_STEP = BIT(2)
    RECOVERY_STEP = BIT(3)
    ENGAGEMENT = BIT(4)
    REVEAL_BATTLE = BIT(5)
    BEGINNING_OF_COMBAT = BIT(6)
    INITIATIVE = BIT(7)
    STRIKE_PHASE = BIT(8)


class QUERY_FLAGS(IntFlag):
    NONE = 0
    CODE = BIT(1)
    FACE_UP = BIT(2)
    SUPERTYPE = BIT(3)
    ORIGINAL_SUBTYPE = BIT(4)
    SUBTYPE = BIT(5)
    ORIGINAL_TRIBE = BIT(6)
    TRIBE = BIT(7)
    MUGIC_ABILITY = BIT(8)
    MUGIC = BIT(9)
    ORIGINAL_ENERGY = BIT(10)
    ENERGY = BIT(11)
    DAMAGE = BIT(12)
    ORIGINAL_WISDOM = BIT(13)
    WISDOM = BIT(14)
    ORIGINAL_COURAGE = BIT(15)
    COURAGE = BIT(16)
    ORIGINAL_POWER = BIT(17)
    POWER = BIT(18)
    ORIGINAL_SPEED = BIT(19)
    SPEED = BIT(20)
    ORIGINAL_ELEMENTS = BIT(21)
    ELEMENTS = BIT(22)
    BATTLEGEAR = BIT(23)
    TARGETS = BIT(24)
    COUNTERS = BIT(25)
    OWNER = BIT(26)
    INFECTED = BIT(27)
    BRAINWASHED = BIT(28)
    NEGATED = BIT(29)
    PUBLIC = BIT(30)
    CASTABLE_MUGIC = BIT(31)